development:
  smtp_username: <%= ENV['DEMO_SMTP_USERNAME'] %>
  smtp_password: <%= ENV['DEMO_SMTP_PASSWORD'] %>
  
test:
  smtp_username: <%= ENV['DEMO_SMTP_USERNAME'] %>
  smtp_password: <%= ENV['DEMO_SMTP_PASSWORD'] %>
production:
  smtp_username: <%= ENV['DEMO_SMTP_USERNAME'] %>
  smtp_password: <%= ENV['DEMO_SMTP_PASSWORD'] %>